# Probe whether the custom dimension is available after reload.
data modify storage neac: DimensionGenerated set value 0b
execute store success storage neac: DimensionGenerated byte 1 in neac: run help help .
execute unless data storage neac: {DimensionGenerated:1b} run tellraw @a {"text":"Player Motion: the neac: dimension is unavailable. Reload the world to generate it.","color":"red"}

# Keep the rotation marker's chunks loaded and create it idempotently.
execute if data storage neac: {DimensionGenerated:1b} in neac: run forceload add -1 -1 1 1
execute if data storage neac: {DimensionGenerated:1b} in neac: unless entity @e[nbt={UUID:[I;5636,369366532,369360896,5636]},limit=1] run summon marker 0.0 0.0 0.0 {UUID:[I;5636,369366532,369360896,5636]}
