
# ディメンション生成のチェック
  data modify storage neac: DimensionGenerated set value 0b
  execute store success storage neac: DimensionGenerated byte 1 in neac: run help help .
  execute unless data storage neac: {DimensionGenerated:1b} run tellraw @a {"text":"==============================\nディメンションの生成を確認できませんでした。\n生成にはワールドの再読み込みが必要です。\n==============================","color":"#ff0000"}

# 追加ディメンションに対してforceloadと固定UUIDのmarkerの設置を行う
  execute if data storage neac: {DimensionGenerated:1b} in neac: run forceload add -1 -1 1 1
  execute if data storage neac: {DimensionGenerated:1b} in neac: run summon marker 0.0 0.0 0.0 {UUID:[I;5636,369366532,369360896,5636]}

